import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";
import NavbarMain from "@/components/Navbar-main";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Password Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
      <SessionWrapper>
        <NavbarMain/>
        <div className="min-h-[86vh] bg-blue-300">
        {children}
        </div>
        <Footer/>
    </SessionWrapper>
        </body>
    </html>
  );
}
